AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ScrumPoker Service - Lambda + DynamoDB with WebSocket support

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  DomainName:
    Type: String
    Default: api.instantscrumpoker.com
    Description: Custom domain name for API Gateway
  
  CertificateArn:
    Type: String
    Default: ""
    Description: ACM Certificate ARN for custom domain (must be in us-east-1). Leave empty to skip custom domain setup.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        ROOMS_TABLE: !Ref RoomsTable
        TABLE_NAME: !Ref RoomsTable  # Keep for backward compatibility
        CONNECTIONS_TABLE: !Ref ConnectionsTable

Resources:
  # ============================================================================
  # DYNAMODB TABLE - Rooms and Data
  # ============================================================================
  RoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub scrumpoker-rooms-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: scrumpoker

  # ============================================================================
  # DYNAMODB TABLE - WebSocket Connections
  # ============================================================================
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub scrumpoker-connections-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: scrumpoker

  # ============================================================================
  # IAM ROLE - Lambda Execution Role
  # ============================================================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ScrumPokerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DynamoDB access
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt RoomsTable.Arn
                  - !Sub '${RoomsTable.Arn}/index/*'
                  - !GetAtt ConnectionsTable.Arn
                  - !Sub '${ConnectionsTable.Arn}/index/*'
              # API Gateway Management API (for WebSocket)
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/${Environment}/*'

  # ============================================================================
  # HTTP API GATEWAY
  # ============================================================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub scrumpoker-api-${Environment}
      CorsConfiguration:
        AllowOrigins:
          - 'https://instantscrumpoker.com'
          - 'https://www.instantscrumpoker.com'
          - 'http://localhost:3000'
          - 'http://localhost:3001'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
        AllowCredentials: true
        ExposeHeaders:
          - Content-Length
          - Content-Type
        MaxAge: 3600

  # ============================================================================
  # API GATEWAY CUSTOM DOMAIN (Optional - requires ACM certificate)
  # ============================================================================
  # Note: To use custom domain:
  # 1. Create ACM certificate for api.instantscrumpoker.com in us-east-1
  # 2. Validate certificate via DNS (add CNAME in Cloudflare)
  # 3. Set CertificateArn parameter to the certificate ARN
  # 4. Deploy template
  # 
  # Alternative: Use Cloudflare CNAME without Custom Domain (current setup)
  # Cloudflare will proxy, but API Gateway may require Host header matching
  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: HasCertificate
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArn
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  ApiDomainMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: HasCertificate
    DependsOn: ApiDomainName
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref ApiDomainName
      Stage: !Ref Environment
      ApiMappingKey: api  # Base path mapping - /api prefix

  # Condition to only create Custom Domain if certificate is provided
  HasCertificate:
    Fn::Not:
      - Fn::Equals:
          - !Ref CertificateArn
          - ""

  # ============================================================================
  # WEBSOCKET API GATEWAY
  # ============================================================================
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub scrumpoker-websocket-${Environment}
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: '$request.body.action'

  WebSocketApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: !Sub ${Environment}
      AutoDeploy: true

  # ============================================================================
  # LAMBDA FUNCTIONS - HTTP API Handlers
  # ============================================================================
  CreateRoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-create-room-${Environment}
      Handler: handlers/createRoom.handler
      CodeUri: ./lambda-build/
      Description: Create a new ScrumPoker room
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        HttpApiEventPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms
            Method: post
        HttpApiEventOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms
            Method: options
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  GetRoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-get-room-${Environment}
      Handler: handlers/getRoom.handler
      CodeUri: ./lambda-build/
      Description: Get room data
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        HttpApiEventGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}
            Method: get
        HttpApiEventOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}
            Method: options
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  JoinRoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-join-room-${Environment}
      Handler: handlers/joinRoom.handler
      CodeUri: ./lambda-build/
      Description: Join a room
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          WS_ENDPOINT: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
      Events:
        HttpApiEventPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}/join
            Method: post
        HttpApiEventOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}/join
            Method: options
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  VoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-vote-${Environment}
      Handler: handlers/vote.handler
      CodeUri: ./lambda-build/
      Description: Submit a vote
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          WS_ENDPOINT: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
      Events:
        HttpApiEventPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}/vote
            Method: post
        HttpApiEventOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}/vote
            Method: options
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  RevealVotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-reveal-votes-${Environment}
      Handler: handlers/revealVotes.handler
      CodeUri: ./lambda-build/
      Description: Reveal votes to all participants
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          WS_ENDPOINT: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
      Events:
        HttpApiEventPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}/reveal
            Method: post
        HttpApiEventOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/rooms/{roomId}/reveal
            Method: options
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  # ============================================================================
  # LAMBDA FUNCTIONS - WebSocket Handlers
  # ============================================================================
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-websocket-connect-${Environment}
      Handler: handlers/websocket/connect.handler
      CodeUri: ./lambda-build/
      Description: WebSocket connection handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-websocket-disconnect-${Environment}
      Handler: handlers/websocket/disconnect.handler
      CodeUri: ./lambda-build/
      Description: WebSocket disconnection handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  WebSocketDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scrumpoker-websocket-default-${Environment}
      Handler: handlers/websocket/default.handler
      CodeUri: ./lambda-build/
      Description: WebSocket message handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Tags:
        Environment: !Ref Environment
        Service: scrumpoker

  # ============================================================================
  # WEBSOCKET API ROUTES
  # ============================================================================
  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      Target: !Sub 'integrations/${WebSocketConnectIntegration}'

  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      Target: !Sub 'integrations/${WebSocketDisconnectIntegration}'

  WebSocketDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      Target: !Sub 'integrations/${WebSocketDefaultIntegration}'

  # ============================================================================
  # WEBSOCKET API INTEGRATIONS
  # ============================================================================
  WebSocketConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations'

  WebSocketDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations'

  WebSocketDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDefaultFunction.Arn}/invocations'

  # ============================================================================
  # LAMBDA PERMISSIONS FOR WEBSOCKET
  # ============================================================================
  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketConnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$connect'

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketDisconnectFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$disconnect'

  WebSocketDefaultPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSocketDefaultFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*/$default'

Outputs:
  HttpApiUrl:
    Description: HTTP API Gateway URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub scrumpoker-http-api-url-${Environment}

  WebSocketApiUrl:
    Description: WebSocket API Gateway URL
    Value: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub scrumpoker-websocket-api-url-${Environment}

  RoomsTableName:
    Description: Rooms DynamoDB Table Name
    Value: !Ref RoomsTable
    Export:
      Name: !Sub scrumpoker-rooms-table-${Environment}

  ConnectionsTableName:
    Description: Connections DynamoDB Table Name
    Value: !Ref ConnectionsTable
    Export:
      Name: !Sub scrumpoker-connections-table-${Environment}

